pool:
  name: Hosted VS2017
  demands:
  - msbuild
  - java
  - visualstudio
  - vstest
  - azureps

#Your build pipeline references the ‘BuildPlatform’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references an undefined variable named ‘Parameters.ArtifactName’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$/MusicSite.sln'

- task: SonarSource.sonarqube.15B84CA1-B62F-4A2A-A403-89B77A063157.SonarQubeScannerMsBuildBegin@3
  displayName: 'Prepare the SonarQube analysis'
  inputs:
    projectKey: selvan123
    projectName: MvcAffableBean
    connectedServiceName: 'SonarQube Cloud'
    cmdLineArgs: '/o:selvan123-github'

- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '$/MusicSite.sln'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true  /p:PackageLocation="$(build.artifactstagingdirectory)\\"              '
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: VSTest@2
  displayName: 'NUnit Test Execution'
  inputs:
    testAssemblyVer2: |
     **\$(BuildConfiguration)\*unittest*.dll
     !**\obj\**
    codeCoverageEnabled: true
    diagnosticsEnabled: True

- task: SonarSource.sonarqube.6D01813A-9589-4B15-8491-8164AEB38055.SonarQubeScannerMsBuildEnd@3
  displayName: 'Complete the SonarQube analysis'

- task: PublishSymbols@1
  displayName: 'Publish symbols path'
  inputs:
    SearchPattern: '**\bin\**\*.pdb'
  continueOnError: true

- task: Veracode.veracode-vsts-build-extension.veracode-scanner-task.Veracode@2
  displayName: 'Upload and scan: $(build.artifactstagingdirectory)'
  inputs:
    ConnectionDetailsSelection: Credentials
    username: 'selvan.s@capgemini.com'
    password: 'Veracode1@34'
    veracodeAppProfile: MvcAffableBean
    failBuildOnPolicyFail: true
  enabled: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: '$(Parameters.ArtifactName)'

- task: AzureResourceGroupDeployment@2
  displayName: 'ARM - Azure QA Environment Provisioning (Web + SQL DB)'
  inputs:
    azureSubscription: 'Visual Studio Enterprise – MPN (8dd549a5-a0ea-4590-8c78-d22e3a52b273)'
    resourceGroupName: 'DevOps_rg'
    location: 'East US'
    csmFile: '$/DemoProject/ARM/azuredeploy.json'
    csmParametersFile: '$/DemoProject/ARM/azuredeploy.parameters.json'

- task: AzureRmWebAppDeployment@3
  displayName: 'Azure QA Deployment'
  inputs:
    azureSubscription: 'Visual Studio Enterprise – MPN (8dd549a5-a0ea-4590-8c78-d22e3a52b273)'
    WebAppName: CapgeminiDemoQA
    Package: '$(build.artifactstagingdirectory)\MvcAffableBean.zip'

- task: VSTest@2
  displayName: 'UI Test Execution using Selenium'
  inputs:
    testAssemblyVer2: |
     **\*uitest*.dll
     !**\obj\**
    diagnosticsEnabled: True

- task: QuickPerfTest@1
  displayName: 'Quick Web Performance Test Performance Test'
  inputs:
    websiteUrl: 'http://CapgeminiDemoQA.azurewebsites.net'
    testName: 'Performance Test'
    runDuration: 180
    avgResponseTimeThreshold: 400

- task: AzureResourceGroupDeployment@2
  displayName: 'ARM - Azure Prod Environment Provisioning'
  inputs:
    azureSubscription: 'Visual Studio Enterprise – MPN (8dd549a5-a0ea-4590-8c78-d22e3a52b273)'
    resourceGroupName: 'DevOps_rg'
    location: 'East US'
    csmFile: '$/DemoProject/ARM/azuredeployProd.json'
    csmParametersFile: '$/DemoProject/ARM/azuredeploy.parametersProd.json'

- task: AzureRmWebAppDeployment@3
  displayName: 'Azure Prod Deployment'
  inputs:
    azureSubscription: 'Visual Studio Enterprise – MPN (8dd549a5-a0ea-4590-8c78-d22e3a52b273)'
    WebAppName: CapgeminiDemoProd
    Package: '$(build.artifactstagingdirectory)\MvcAffableBean.zip'
